version: "3.8"

services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8090:80" # внутри контейнера порт 80, наружу 8090
    volumes:
      - ./pocketbase_data:/pb_data # монтируем папку с данными из текущей директории
    restart: unless-stopped

  swagger-ui:
    build: ./swagger # папка с Dockerfile и api.yaml
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_UI_THEME=light
    restart: unless-stopped
